apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: TBDNAME
  namespace: TBDNAMESPACE
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins: []
    additionalConfig: |
      log.console.level = debug
