apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: TBDNAME
  namespace: TBDNAMESPACE
spec:
  replicas: 3
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  resources:
    requests:
      cpu: 4
      memory: 10Gi
    limits:
      cpu: 4
      memory: 10Gi
  persistence:
    storage: 50Gi
