apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: rabbitmq
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: rabbitmqs.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: rabbitmq
        plural: rabbitmqs
        singular: rabbitmq
      scope: Namespaced
      versions:
      - name: v1alpha1
        schema:
          openAPIV3Schema:
            properties:
              spec:
                properties:
                  env:
                    default: dev
                    description: |
                      Configures and deploys RabbitMQ with environment specific configuration. Dev RabbitMQ is created with a single replica and Debug log level.
                    pattern: ^(dev|prod)$
                    type: string
                  plugins:
                    default: []
                    description: List of additional plugins to be included in the
                      installation
                    example:
                    - rabbitmq_federation
                    - rabbitmq_federation_management
                    items:
                      type: string
                    type: array
                type: object
            type: object
        served: true
        storage: true
  workflows:
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: instance-configure
          namespace: default
        spec:
          containers:
          - image: ghcr.io/syntasso/promise-rabbitmq/rabbitmq-configure-pipeline:v0.1.0
            name: rabbitmq-configure-pipeline
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
          namespace: default
        spec:
          containers:
          - image: ghcr.io/syntasso/promise-rabbitmq/rabbitmq-configure-pipeline:v0.1.0
            name: rabbitmq-configure-pipeline
