#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

urls=(
    "https://github.com/rabbitmq/cluster-operator/releases/download/v2.9.0/cluster-operator.yml"
)

mkdir -p $PWD/resources
rm -rf $PWD/resources/*

mkdir -p $PWD/configure-pipeline/dependencies

for url in "${urls[@]}"; do
    curl -sL $url | sed 's/rabbitmq-system/default/g' > $PWD/configure-pipeline/dependencies/$(basename $url)
done
