#!/usr/bin/env bash

PWD="$( cd $(dirname $0)/.. && pwd)"

rdir="$PWD/configure-pipeline/resources/"
rm -rf "${rdir}"
mkdir -p "${rdir}"

# configurations taken from https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/production-ready/rabbitmq.yaml
cat > "${rdir}/prod-rabbitmq-instance.yaml" <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: TBDNAME
  namespace: TBDNAMESPACE
spec:
  replicas: 3
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  resources:
    requests:
      cpu: 4
      memory: 10Gi
    limits:
      cpu: 4
      memory: 10Gi
  persistence:
    storage: 50Gi
EOF

cat > "${rdir}/dev-rabbitmq-instance.yaml" <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: TBDNAME
  namespace: TBDNAMESPACE
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins: []
    additionalConfig: |
      log.console.level = debug
EOF
