FROM "alpine"

LABEL org.opencontainers.image.authors "kratix@syntasso.io"
LABEL org.opencontainers.image.source https://github.com/syntasso/promise-rabbitmq

RUN [ "mkdir", "/tmp/transfer" ]
RUN apk update && apk add --no-cache yq

COPY resources /tmp/transfer/resources
COPY dependencies /tmp/transfer/dependencies
COPY execute-pipeline execute-pipeline

CMD [ "sh", "-c", "./execute-pipeline" ]
ENTRYPOINT []
