#!/usr/bin/env sh

set -eux

if [ $KRATIX_WORKFLOW_TYPE == "promise" ]; then
  cp /tmp/transfer/dependencies/* /kratix/output/
else
  namespace="default"

  # Read current values from the provided resource request
  name="$(yq eval '.metadata.name' /kratix/input/object.yaml)"
  env_type="$(yq eval '.spec.env // "dev"' /kratix/input/object.yaml)"

  base_instance="/tmp/transfer/resources/${env_type}-rabbitmq-instance.yaml"

  export plugins="$(yq eval '.spec.plugins // []' /kratix/input/object.yaml)"

  # Replace defaults with user provided values
  yq eval '.spec.rabbitmq.additionalPlugins = env(plugins)' ${base_instance} |
    sed "s/TBDNAMESPACE/${namespace}/g" |
    sed "s/TBDNAME/${name}/g" > /kratix/output/instance.yaml
fi
